version: "3.3"

services:
  B:
    image: vincentserpoul/paritypoa:v1.6.8
    ports:
      - "8081:8081"
      - "8181:8181"
      - "8546:8546"
      - "30304:30304"
    environment:
      - UI_PORT=8181
      - JSONRPC_PORT=8546
      - NETWORK_PORT=30304
      - DAPPS_PORT=8081
      - AUTHORITY_COMPANY=B
    volumes:
      - chaindata_B:/mnt/io.parity.ethereum
    secrets:
      - authority.B.address
      - authority.B.passphrase
      - authority.B.password
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=A]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chaindata_B:

networks:
  default:
    external:
      name: poa_default

secrets:
  authority.B.address:
    external: true
  authority.B.passphrase:
    external: true
  authority.B.password:
    external: true