[parity]
chain = "/etc/parityPoA/PoA.json"
base_path = "/mnt/io.parity.ethereum"

[rpc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "signer", "personal", "parity_accounts", "parity_set"]
interface = "127.0.0.1"